/**
 * Exported report — one self-contained, printable HTML file per analysis.
 *
 * Everything the workbench shows on screen goes in, including the AI diagnosis
 * (which is why the summary is lifted into ReportContext rather than kept in the
 * panel that generated it). No network requests, no scripts: the file opens the
 * same way in five years as it does today, which is the point of a post-mortem
 * artefact that gets attached to a ticket.
 *
 * Ranked tables are capped at TOP_N to match the UI — a report is a hand-off
 * document, not a data dump.
 */
import { parseMarkdown, parseInline } from './markdown'

export const TOP_N = 10

// ---------------------------------------------------------------- formatting

export function fmtBytes(n) {
  if (n == null) return '—'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  let i = 0
  let v = n
  while (v >= 1024 && i < units.length - 1) { v /= 1024; i++ }
  return `${v.toFixed(i === 0 ? 0 : 1)} ${units[i]}`
}

const fmtNum = (n) => (n == null ? '—' : Number(n).toLocaleString())

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// ------------------------------------------------------------------ markdown

function inlineHtml(text) {
  return parseInline(text)
    .map((p) => {
      if (p.kind === 'bold') return `<strong>${esc(p.text)}</strong>`
      if (p.kind === 'code') return `<code>${esc(p.text)}</code>`
      return esc(p.text)
    })
    .join('')
}

function markdownHtml(text) {
  return parseMarkdown(text)
    .map((b) => {
      if (b.type === 'heading') {
        const level = Math.min(b.level + 1, 6)   // demote: the page owns <h1>
        return `<h${level}>${inlineHtml(b.text)}</h${level}>`
      }
      if (b.type === 'code') return `<pre><code>${esc(b.text)}</code></pre>`
      if (b.type === 'ul') return `<ul>${b.items.map((i) => `<li>${inlineHtml(i)}</li>`).join('')}</ul>`
      if (b.type === 'ol') return `<ol>${b.items.map((i) => `<li>${inlineHtml(i)}</li>`).join('')}</ol>`
      return `<p>${inlineHtml(b.text)}</p>`
    })
    .join('\n')
}

// -------------------------------------------------------------- html helpers

function table(headers, rows, aligns = []) {
  if (!rows.length) return ''
  const th = headers
    .map((h, i) => `<th${aligns[i] === 'r' ? ' class="r"' : ''}>${esc(h)}</th>`)
    .join('')
  const body = rows
    .map((r) => `<tr>${r.map((c, i) =>
      `<td${aligns[i] === 'r' ? ' class="r"' : ''}>${c}</td>`).join('')}</tr>`)
    .join('\n')
  return `<table><thead><tr>${th}</tr></thead><tbody>${body}</tbody></table>`
}

function section(title, inner, note) {
  if (!inner) return ''
  return `<section><h2>${esc(title)}</h2>${
    note ? `<p class="note">${esc(note)}</p>` : ''
  }${inner}</section>`
}

/** "showing 10 of 312" — the report must never imply a truncated table is whole. */
function capNote(shown, total) {
  return total > shown ? `Showing the top ${shown} of ${fmtNum(total)}.` : null
}

// ---------------------------------------------------------------- AI section

function llmSection(llm) {
  if (!llm) {
    return section(
      'AI diagnosis',
      `<p class="note">No AI diagnosis was generated for this analysis. Open the
       “AI diagnosis” panel in the workbench and run it before exporting to
       include a written root-cause write-up here.</p>`,
    )
  }
  return `<section class="ai"><h2>AI diagnosis</h2>
    <p class="note">Generated by Claude from the structured findings below.
    Read it alongside the evidence — it interprets the data, it does not add to it.</p>
    <div class="md">${markdownHtml(llm)}</div></section>`
}

// ------------------------------------------------------------------ coverage

function coverageSection(a) {
  const skipped = a.skipped_analyses || []
  if (!a.truncated && skipped.length === 0) return ''
  const bits = []
  if (a.truncated) {
    bits.push(`<p class="warn"><strong>Partial analysis.</strong> Only
      ${esc(fmtBytes(a.analyzed_bytes))} of this ${esc(fmtBytes(a.file_size_bytes))}
      dump was read (quick mode). Every count and percentage in this report describes
      that prefix, not the whole heap.</p>`)
  }
  if (skipped.length) {
    bits.push(`<p>Stages that did not run on this dump:</p><ul>${
      skipped.map((s) =>
        `<li><strong>${esc(s.stage)}</strong> — ${esc(s.reason)}${
          s.enable_hint ? ` <em>(${esc(s.enable_hint)})</em>` : ''
        }</li>`).join('')
    }</ul>`)
  }
  return `<section class="coverage"><h2>Coverage</h2>${bits.join('\n')}</section>`
}

// ------------------------------------------------------------------ findings

function findingsSection(findings) {
  if (!findings?.length) return ''
  const cards = findings.map((f) => {
    const parts = [`<p>${inlineHtml(f.description || '')}</p>`]
    if (f.impact) parts.push(`<p><span class="k">Impact</span> ${inlineHtml(f.impact)}</p>`)
    if (f.likely_cause) parts.push(`<p><span class="k">Likely cause</span> ${inlineHtml(f.likely_cause)}</p>`)
    if (f.evidence?.length) {
      parts.push(`<p><span class="k">Evidence</span></p><ul>${
        f.evidence.map((e) => `<li>${inlineHtml(e)}</li>`).join('')}</ul>`)
    }
    if (f.remediation) parts.push(`<p><span class="k">Fix</span> ${inlineHtml(f.remediation)}</p>`)
    for (const loc of f.source_locations || []) {
      const where = loc.repo_path
        ? `${loc.repo_path}:${loc.line ?? '?'}`
        : `${loc.class_name}.${loc.method}${loc.line ? `:${loc.line}` : ''}`
      parts.push(`<p class="loc">${esc(where)}</p>`)
      if (loc.snippet?.lines?.length) {
        const start = loc.snippet.start_line
        parts.push(`<pre class="snippet">${loc.snippet.lines.map((line, k) => {
          const ln = start + k
          const hl = ln === loc.snippet.highlight_line
          return `<span class="${hl ? 'hl' : ''}">${String(ln).padStart(5)}  ${esc(line)}</span>`
        }).join('\n')}</pre>`)
      }
    }
    return `<article class="finding sev-${esc(f.severity)}">
      <h3><span class="sev">${esc(f.severity)}</span> ${inlineHtml(f.title)}</h3>
      ${parts.join('\n')}
    </article>`
  })
  return section('Diagnostic findings', cards.join('\n'))
}

// ------------------------------------------------------- per-kind body parts

function heapBody(a) {
  const out = []

  out.push(section('At a glance', table(
    ['metric', 'value'],
    [
      ['file size', esc(fmtBytes(a.file_size_bytes))],
      ...(a.truncated ? [['bytes analyzed', esc(fmtBytes(a.analyzed_bytes))]] : []),
      ['instances', esc(fmtNum(a.total_instances))],
      ['classes loaded', esc(fmtNum(a.total_classes_loaded))],
      ['String instances', esc(fmtNum(a.total_strings))],
      ...(a.reachable_bytes != null ? [['reachable heap', esc(fmtBytes(a.reachable_bytes))]] : []),
      ...(a.unreachable_bytes ? [['unreachable (uncollected garbage)', esc(fmtBytes(a.unreachable_bytes))]] : []),
      ...(a.wasted_bytes_estimate ? [['reclaimable duplicates', esc(fmtBytes(a.wasted_bytes_estimate))]] : []),
      ...(a.sizing_model ? [['object layout assumed', esc(a.sizing_model)]] : []),
    ].map(([k, v]) => [esc(k), v]),
    ['l', 'r'],
  )))

  const dom = (a.dominators || []).slice(0, TOP_N)
  out.push(section(
    'Biggest objects by retained size',
    table(
      ['object', 'retained', '% heap', 'shallow'],
      dom.map((d) => [
        `<code>${esc(d.class_name)}</code> <span class="dim">@${esc(d.object_id)}</span>${
          d.chain?.length ? `<div class="dim">⤷ ${esc(d.chain.join(' → '))}</div>` : ''}`,
        esc(fmtBytes(d.retained_bytes)),
        `${esc(d.pct_of_reachable)}%`,
        esc(fmtBytes(d.shallow_bytes)),
      ]),
      ['l', 'r', 'r', 'r'],
    ),
    capNote(dom.length, (a.dominators || []).length),
  ))

  const deps = (a.deployments || []).slice(0, TOP_N)
  out.push(section(
    'Deployments (classloaders & artifacts)',
    table(
      ['artifact / classloader', 'classes', 'shallow', 'live threads'],
      deps.map((d) => [
        `<code>${esc(d.name || d.id)}</code>${d.stale ? ' <span class="tag">stale</span>' : ''}
         <div class="dim">${esc(d.loader_class)}</div>`,
        esc(fmtNum(d.class_count)),
        esc(fmtBytes(d.shallow_size_bytes)),
        esc(fmtNum(d.live_thread_count)),
      ]),
      ['l', 'r', 'r', 'r'],
    ),
    capNote(deps.length, (a.deployments || []).length),
  ))

  const dups = (a.duplicate_classes || []).slice(0, TOP_N)
  out.push(section(
    'Duplicate classes',
    table(
      ['class', 'loaders'],
      dups.map((d) => [`<code>${esc(d.class_name)}</code>`, esc(d.loader_count)]),
      ['l', 'r'],
    ),
    capNote(dups.length, (a.duplicate_classes || []).length),
  ))

  const bySize = (a.top_classes_by_size || []).slice(0, TOP_N)
  out.push(section(
    'Histogram — top classes by shallow size',
    table(
      ['class', 'instances', 'shallow size', '% heap'],
      bySize.map((e) => [
        `<code>${esc(e.class_name)}</code>`,
        esc(fmtNum(e.instance_count)),
        esc(fmtBytes(e.shallow_size_bytes)),
        e.pct_of_total_size != null ? `${esc(e.pct_of_total_size)}%` : '—',
      ]),
      ['l', 'r', 'r', 'r'],
    ),
    capNote(bySize.length, (a.top_classes_by_size || []).length),
  ))

  const byCount = (a.top_classes_by_count || []).slice(0, TOP_N)
  out.push(section(
    'Histogram — top classes by instance count',
    table(
      ['class', 'instances', 'shallow size'],
      byCount.map((e) => [
        `<code>${esc(e.class_name)}</code>`,
        esc(fmtNum(e.instance_count)),
        esc(fmtBytes(e.shallow_size_bytes)),
      ]),
      ['l', 'r', 'r'],
    ),
    capNote(byCount.length, (a.top_classes_by_count || []).length),
  ))

  return out.join('\n')
}

function threadBody(a) {
  const out = []
  out.push(section('At a glance', table(
    ['metric', 'value'],
    [
      ['total threads', fmtNum(a.total_threads)],
      ['daemon threads', fmtNum(a.daemon_count)],
      ['deadlocks', fmtNum(a.deadlocks?.length || 0)],
      ...Object.entries(a.state_breakdown || {}).map(([k, v]) => [k, fmtNum(v)]),
    ].map(([k, v]) => [esc(k), esc(v)]),
    ['l', 'r'],
  )))

  const pools = (a.pools || []).slice(0, TOP_N)
  out.push(section(
    'Thread pools',
    table(
      ['pool', 'threads', 'busy', 'blocked', 'health'],
      pools.map((p) => [
        `<code>${esc(p.name)}</code>${p.note ? `<div class="dim">${esc(p.note)}</div>` : ''}`,
        esc(fmtNum(p.total)),
        `${esc(p.busy_pct)}%`,
        `${esc(p.blocked_pct)}%`,
        esc(p.health),
      ]),
      ['l', 'r', 'r', 'r', 'l'],
    ),
    capNote(pools.length, (a.pools || []).length),
  ))

  const groups = (a.stack_groups || []).slice(0, TOP_N)
  out.push(section(
    'Threads clustered by top-of-stack',
    table(
      ['top frames', 'threads'],
      groups.map((g) => [
        `<pre class="frames">${esc((g.top_frames || []).join('\n'))}</pre>`,
        esc(fmtNum(g.count)),
      ]),
      ['l', 'r'],
    ),
    capNote(groups.length, (a.stack_groups || []).length),
  ))

  const hot = (a.hot_threads || []).slice(0, TOP_N)
  out.push(section(
    'Hottest threads by CPU',
    table(
      ['thread', 'cpu', 'state'],
      hot.map((t) => [
        `<code>${esc(t.name)}</code>${t.top_frame ? `<div class="dim">${esc(t.top_frame)}</div>` : ''}`,
        `${esc(t.cpu_pct)}%`,
        esc(t.state),
      ]),
      ['l', 'r', 'l'],
    ),
    capNote(hot.length, (a.hot_threads || []).length),
  ))
  return out.join('\n')
}

function gcBody(a) {
  return section('At a glance', table(
    ['metric', 'value'],
    [
      ['collector', a.collector],
      ['log format', a.jdk_logging],
      ['window', `${Number(a.duration_s || 0).toFixed(0)} s`],
      ['collections', fmtNum(a.gc_count)],
      ['full GCs', fmtNum(a.full_gc_count)],
      ['throughput', `${a.throughput_pct}%`],
      ['pause p50 / p95 / p99 / max',
        `${a.pause_p50_ms} / ${a.pause_p95_ms} / ${a.pause_p99_ms} / ${a.pause_max_ms} ms`],
      ['allocation rate', `${a.alloc_rate_mb_s} MB/s`],
      ['post-GC heap trend', `${a.heap_after_trend_mb_per_min} MB/min`],
    ].map(([k, v]) => [esc(k), esc(v)]),
    ['l', 'r'],
  ))
}

// ---------------------------------------------------------------------- page

const KIND_LABEL = { heap: 'Heap dump', thread: 'Thread dump', gc: 'GC log' }

const CSS = `
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { margin: 0; padding: 2.5rem 1.5rem 4rem; background: #fbfaf8; color: #1c1b19;
  font: 15px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 60rem; margin: 0 auto; }
h1 { font-size: 1.7rem; margin: 0 0 .25rem; letter-spacing: -.02em; }
h2 { font-size: 1.05rem; margin: 2.5rem 0 .75rem; letter-spacing: .04em;
  text-transform: uppercase; color: #6b665e; border-bottom: 1px solid #e2ded6;
  padding-bottom: .4rem; }
h3 { font-size: 1rem; margin: 0 0 .5rem; }
p { margin: .5rem 0; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .86em;
  background: #f0ede7; padding: .1em .35em; border-radius: 3px; }
pre { background: #f4f2ee; border: 1px solid #e2ded6; border-radius: 6px;
  padding: .75rem; overflow-x: auto; font-family: ui-monospace, Menlo, monospace;
  font-size: .8rem; line-height: 1.55; }
pre code { background: none; padding: 0; }
.dim { color: #7a746b; font-size: .85em; }
.note { color: #6b665e; font-size: .88rem; }
.warn { background: #fff4e5; border-left: 3px solid #d98324; padding: .6rem .8rem;
  border-radius: 0 4px 4px 0; }
header .meta { color: #6b665e; font-size: .88rem; }
.verdict { border: 1px solid #e2ded6; border-radius: 8px; padding: 1rem 1.2rem;
  margin: 1.5rem 0; background: #fff; }
.verdict.critical { border-color: #d1453b; background: #fdf3f2; }
.verdict.degraded { border-color: #d98324; background: #fff8ef; }
.verdict.healthy  { border-color: #4a8a52; background: #f4faf4; }
.verdict .v { font-weight: 600; text-transform: uppercase; font-size: .75rem;
  letter-spacing: .08em; }
table { width: 100%; border-collapse: collapse; margin: .5rem 0 1rem; font-size: .9rem; }
th, td { text-align: left; padding: .45rem .6rem; border-bottom: 1px solid #eae6df;
  vertical-align: top; }
th { font-size: .72rem; text-transform: uppercase; letter-spacing: .06em;
  color: #7a746b; border-bottom-color: #d8d3ca; }
td.r, th.r { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
.finding { border: 1px solid #e2ded6; border-left-width: 3px; border-radius: 6px;
  padding: .9rem 1.1rem; margin: .75rem 0; background: #fff; }
.finding.sev-critical { border-left-color: #d1453b; }
.finding.sev-warning  { border-left-color: #d98324; }
.finding.sev-info     { border-left-color: #4573b8; }
.sev { font-size: .68rem; text-transform: uppercase; letter-spacing: .07em;
  padding: .12em .45em; border-radius: 3px; background: #efece6; color: #55504a;
  margin-right: .4rem; vertical-align: middle; }
.k { font-size: .7rem; text-transform: uppercase; letter-spacing: .07em;
  color: #7a746b; margin-right: .4rem; }
.loc { font-family: ui-monospace, Menlo, monospace; font-size: .8rem; color: #4573b8; }
.snippet .hl { background: #fdf3d4; display: inline-block; width: 100%; }
.frames { margin: 0; font-size: .75rem; }
.tag { font-size: .68rem; background: #fdf3f2; color: #d1453b; padding: .1em .4em;
  border-radius: 3px; }
section.ai { border: 1px solid #cdd8ea; background: #f7f9fd; border-radius: 8px;
  padding: .25rem 1.2rem 1rem; margin-top: 2rem; }
section.ai h2 { border-bottom-color: #cdd8ea; }
section.coverage { border: 1px solid #e6d9c2; background: #fffbf4; border-radius: 8px;
  padding: .25rem 1.2rem 1rem; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2ded6;
  color: #7a746b; font-size: .8rem; }
@media print { body { padding: 0; background: #fff; } .finding, .verdict { break-inside: avoid; } }
`

export function buildReportHTML({ kind, filename, analysis, llm, generatedAt }) {
  const a = analysis || {}
  const label = KIND_LABEL[kind] || 'Analysis'
  const when = generatedAt || new Date()
  const verdict = a.verdict || 'healthy'
  const body =
    kind === 'heap' ? heapBody(a) :
    kind === 'thread' ? threadBody(a) :
    kind === 'gc' ? gcBody(a) : ''

  const title = `POSTMORTEM — ${label}${filename ? ` — ${filename}` : ''}`

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${CSS}</style>
</head><body><main>
<header>
  <h1>POSTMORTEM — ${esc(label)}</h1>
  <div class="meta">
    ${filename ? `<code>${esc(filename)}</code> · ` : ''}generated ${esc(when.toISOString().replace('T', ' ').replace(/\..+/, ' UTC'))}
  </div>
</header>

<div class="verdict ${esc(verdict)}">
  <div class="v">${esc(verdict)}</div>
  <p>${esc(a.summary || '')}</p>
</div>

${coverageSection(a)}
${llmSection(llm)}
${findingsSection(a.findings)}
${body}

<footer>
  Produced by POSTMORTEM. Ranked tables show the top ${TOP_N} entries; the full
  data stays in the workbench session. Shallow sizes use the
  ${esc(a.sizing_model || 'assumed')} object layout — hprof does not record object
  headers, so that part is inferred, not measured.
</footer>
</main></body></html>`
}

/** Build the report and hand it to the browser as a download. */
export function downloadReport({ kind, filename, analysis, llm }) {
  const html = buildReportHTML({ kind, filename, analysis, llm })
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const stem = (filename || kind || 'analysis').replace(/[^\w.-]+/g, '_')
  const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, '')
  const link = document.createElement('a')
  link.href = url
  link.download = `postmortem-${kind}-${stem}-${stamp}.html`
  document.body.appendChild(link)
  link.click()
  link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
